# Generated by Django 3.1.4 on 2020-12-24 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=100)),
                ('user_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.userlisting')),
            ],
        ),
    ]
