# Generated by Django 3.1.7 on 2021-05-16 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20210510_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auctions.bid'),
        ),
        migrations.AddField(
            model_name='listing',
            name='winner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
