# Generated by Django 3.1.7 on 2021-05-16 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20210517_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auctions.bid'),
        ),
    ]
