# Generated by Django 3.1.7 on 2021-05-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20210520_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='length',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='width',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
