# Generated by Django 3.1.7 on 2021-06-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auto_20210525_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
