# Generated by Django 3.1.7 on 2021-06-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='address',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
