# Generated by Django 3.2.3 on 2021-06-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='end_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
